"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env():
    env_file = BASE_DIR / '.env'
    if not env_file.exists():
        return

    for raw_line in env_file.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_local_env()


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-e%#ykfcr^$&18=*tqsmxp67viq))2h%8f#*4=^q1ob!89^(-2k')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

_allowed_hosts_raw = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if _allowed_hosts_raw.strip():
    ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_raw.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.vercel.app']

_csrf_origins_raw = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_origins_raw.split(',') if origin.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.ProAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True),
    }
else:
    sqlite_name = Path('/tmp/db.sqlite3') if os.environ.get('VERCEL') else BASE_DIR / 'db.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_name,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Email defaults for account activation and password reset flows.
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@mysite.local')
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', False)

# Login brute-force protection settings used by AuthLoginView.
LOGIN_RATE_LIMIT_ATTEMPTS = int(os.environ.get('LOGIN_RATE_LIMIT_ATTEMPTS', '5'))
LOGIN_RATE_LIMIT_WINDOW_SECONDS = int(os.environ.get('LOGIN_RATE_LIMIT_WINDOW_SECONDS', '900'))
LOGIN_RATE_LIMIT_LOCKOUT_SECONDS = int(os.environ.get('LOGIN_RATE_LIMIT_LOCKOUT_SECONDS', '900'))

# When false, users are activated immediately on signup (no email click needed).
ACCOUNT_REQUIRE_EMAIL_VERIFICATION = _env_bool('ACCOUNT_REQUIRE_EMAIL_VERIFICATION', False)

# Enable strong HTTPS and cookie settings when DJANGO_FORCE_HTTPS=true.
DJANGO_FORCE_HTTPS = _env_bool('DJANGO_FORCE_HTTPS', False)
SECURE_SSL_REDIRECT = DJANGO_FORCE_HTTPS
SESSION_COOKIE_SECURE = DJANGO_FORCE_HTTPS
CSRF_COOKIE_SECURE = DJANGO_FORCE_HTTPS
SECURE_HSTS_SECONDS = 31536000 if DJANGO_FORCE_HTTPS else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = DJANGO_FORCE_HTTPS
SECURE_HSTS_PRELOAD = DJANGO_FORCE_HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Pro billing settings
PRO_FEATURES_REQUIRE_PAYMENT = _env_bool('PRO_FEATURES_REQUIRE_PAYMENT', True)
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '').strip()
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '').strip()
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '').strip()
STRIPE_PRO_PRICE_ID = os.environ.get('STRIPE_PRO_PRICE_ID', '').strip()
SHOW_STRIPE_UPGRADE_BUTTON = _env_bool('SHOW_STRIPE_UPGRADE_BUTTON', False)
ALLOW_DEV_PRO_UPGRADE_WITHOUT_STRIPE = _env_bool('ALLOW_DEV_PRO_UPGRADE_WITHOUT_STRIPE', False)
ZAAD_MANUAL_PAYMENT_ENABLED = _env_bool('ZAAD_MANUAL_PAYMENT_ENABLED', True)
ZAAD_MERCHANT_NUMBER = os.environ.get('ZAAD_MERCHANT_NUMBER', '').strip()
ZAAD_PRO_AMOUNT = os.environ.get('ZAAD_PRO_AMOUNT', '5').strip()
ZAAD_PRO_CURRENCY = os.environ.get('ZAAD_PRO_CURRENCY', 'USD').strip().upper()

# Direct payment channels shown on the Pro upgrade page.
PAYMENT_ZAAD_ACCOUNT = os.environ.get('PAYMENT_ZAAD_ACCOUNT', '').strip()
PAYMENT_EVC_ACCOUNT = os.environ.get('PAYMENT_EVC_ACCOUNT', '').strip()
PAYMENT_SAHAL_ACCOUNT = os.environ.get('PAYMENT_SAHAL_ACCOUNT', '').strip()
PAYMENT_BANK_NAME = os.environ.get('PAYMENT_BANK_NAME', '').strip()
PAYMENT_BANK_ACCOUNT = os.environ.get('PAYMENT_BANK_ACCOUNT', '').strip()

_pro_paths_raw = os.environ.get('PRO_ONLY_PATH_PREFIXES', '/api/tokens/create/')
PRO_ONLY_PATH_PREFIXES = tuple(item.strip() for item in _pro_paths_raw.split(',') if item.strip())
PRO_RATE_LIMIT_WINDOW_SECONDS = int(os.environ.get('PRO_RATE_LIMIT_WINDOW_SECONDS', '60'))
PRO_RATE_LIMIT_REQUESTS = int(os.environ.get('PRO_RATE_LIMIT_REQUESTS', '30'))

PRO_RATE_LIMIT_RULES = {
    'ai_assistant': {
        'requests': int(os.environ.get('PRO_RATE_LIMIT_AI_ASSISTANT_REQUESTS', '10')),
        'window_seconds': int(os.environ.get('PRO_RATE_LIMIT_AI_ASSISTANT_WINDOW_SECONDS', '60')),
    },
    'api_labs_post': {
        'requests': int(os.environ.get('PRO_RATE_LIMIT_API_LABS_POST_REQUESTS', '20')),
        'window_seconds': int(os.environ.get('PRO_RATE_LIMIT_API_LABS_POST_WINDOW_SECONDS', '60')),
    },
    'api_lab_delete': {
        'requests': int(os.environ.get('PRO_RATE_LIMIT_API_LAB_DELETE_REQUESTS', '10')),
        'window_seconds': int(os.environ.get('PRO_RATE_LIMIT_API_LAB_DELETE_WINDOW_SECONDS', '60')),
    },
    'api_create_token': {
        'requests': int(os.environ.get('PRO_RATE_LIMIT_API_CREATE_TOKEN_REQUESTS', '3')),
        'window_seconds': int(os.environ.get('PRO_RATE_LIMIT_API_CREATE_TOKEN_WINDOW_SECONDS', '60')),
    },
}
